# Generated by Django 3.0.4 on 2020-03-16 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Not Specified')], max_length=140, verbose_name='gender')),
                ('profile_picture', models.ImageField(default='images/default_profile.jpg', max_length=500, upload_to='images', verbose_name='profile picture')),
                ('telephone', models.CharField(blank=True, max_length=128, verbose_name='telephone')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('linkedin', models.URLField(blank=True, verbose_name='linkedin')),
                ('github', models.URLField(blank=True, verbose_name='github')),
                ('gitlab', models.URLField(blank=True, verbose_name='gitlab')),
                ('facebook', models.URLField(blank=True, verbose_name='facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='twitter')),
                ('google_plus', models.URLField(blank=True, verbose_name='google plus')),
                ('biography', models.TextField(blank=True, verbose_name='biography')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': "profile's",
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='street')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=255, verbose_name='state')),
                ('zip_code', models.CharField(blank=True, max_length=15, verbose_name='zip_code')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': "address's",
                'db_table': 'address',
            },
        ),
    ]
