# Generated by Django 3.0.4 on 2020-03-16 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200316_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 16, 16, 26, 52, 602703), verbose_name='birthday'),
            preserve_default=False,
        ),
    ]
