# Generated by Django 3.0.4 on 2020-03-16 01:03

import apps.blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=500, upload_to=apps.blog.models.create_file_path, verbose_name='Attachment')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('image', models.ImageField(default='images/no_img_available.jpg', max_length=500, upload_to=apps.blog.models.create_image_path, verbose_name='post image')),
                ('content', models.TextField(verbose_name='post content')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': "blog's",
                'db_table': 'blog',
            },
        ),
    ]
