# Generated by Django 3.0.4 on 2020-03-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='qualification_rating',
        ),
    ]
