# Generated by Django 3.0.4 on 2020-03-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_qualification_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default=' ', max_length=256, verbose_name='title'),
            preserve_default=False,
        ),
    ]
