# Generated by Django 3.0.4 on 2020-03-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='job_role',
        ),
        migrations.AddField(
            model_name='experience',
            name='job_description',
            field=models.TextField(blank=True, verbose_name='job role'),
        ),
    ]
