# Generated by Django 3.0.4 on 2020-03-16 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128, verbose_name='description')),
            ],
            options={
                'verbose_name': 'tool_type',
                'verbose_name_plural': "tool_type's",
                'db_table': 'tool_type',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_description', models.CharField(max_length=255, verbose_name='tool or language')),
                ('tool_image', models.CharField(blank=True, max_length=128, verbose_name='tool image(ex:fab fa-html5)')),
                ('qualification_rating', models.IntegerField(blank=True, verbose_name='qualification_rating')),
                ('date_started', models.DateField(blank=True, verbose_name='date started')),
                ('date_ended', models.DateField(blank=True, verbose_name='date ended')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.ToolType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tool',
                'verbose_name_plural': "tool's",
                'db_table': 'tool',
            },
        ),
    ]
