# Generated by Django 3.0.4 on 2020-03-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooltype',
            name='desc_code',
            field=models.CharField(default='', max_length=128, verbose_name='desc_code'),
        ),
    ]
