# Generated by Django 3.0.4 on 2020-03-16 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_tooltype_desc_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='date_ended',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='date_started',
        ),
    ]
