# Generated by Django 3.0.4 on 2020-03-16 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255, verbose_name='school name')),
                ('degree_title', models.CharField(max_length=255, verbose_name='degree title')),
                ('information', models.CharField(blank=True, max_length=255, verbose_name='information')),
                ('gpa', models.FloatField(blank=True, verbose_name='gpa')),
                ('date_started', models.DateField(blank=True, verbose_name='date started')),
                ('date_ended', models.DateField(blank=True, verbose_name='date ended')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'education',
                'verbose_name_plural': "education's",
                'db_table': 'education',
            },
        ),
    ]
